### ISSUE TITLE
Add CD via GitHub Actions workflow

### ISSUE THREAD

**Issue by nkantar** [nkantar/Parsenvy#24]
To-do:

- [x] get CD workflow to work
    - [x] fetch code at tag
    - [x] build wheel
    - [x] install and test wheel locally
    - [x] publish to test PyPI
    - [x] publish to production PyPI
- [x] update CD workflow triggers
- [x] update CI workflow to use shared CI/CD scripts

**Comment by upretip** [comment]
#29 resolves this!
