### ISSUE TITLE
Contributing Page on docs missing.

### ISSUE THREAD

**Issue by anistark** [nkantar/Parsenvy#28]
The [contributing page](https://parsenvy.readthedocs.io/en/latest/CONTRIBUTING.md) on docs seems to be missing.

**Comment by nkantar** [comment]
For additional context: The link in the README that references that file is invalid. The file is present in the repository, and we should probably instead include it the same way the README is included on the index page. Happy to help more.

**Comment by anistark** [comment]
Okay. Working on this.
